name: Publish

on:
  push:
    branches:
      - main 
    tags-ignore:
      - "v**"

jobs:
  build:
    if: "!contains(github.event.head_commit.author.name, 'Github Action')"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Configure CI Git User
        run: |
          git config --global user.name 'Github Action'
          git config --global user.email 'morten-olsen@users.noreply.github.com'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_PAT@github.com/morten-olsen/rolighed
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout and pull branch
        run: git checkout "${GITHUB_REF:11}" && git pull
        
      - uses: actions/setup-node@v1
        with:
          node-version: '15.x'
          registry-url: 'https://npm.pkg.github.com'

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> .npmrc
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install Packages
        run: yarn install

      - name: Publish package
        run: "yarn lerna publish prerelease --yes --message 'chore: release new versions %s' --force-publish"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GH_TOKEN}}
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
